package(default_visibility = ["//visibility:public"])

filegroup(
    name = "diagnostics",
    srcs = glob(["diagnostics/**/*"]),
)

filegroup(
    name = "schema",
    srcs = glob(["schema/**/*"]),
)

filegroup(
    name = "syntax",
    srcs = glob(["syntax/**/*"]),
)

filegroup(
    name = "tokens",
    srcs = glob(["tokens/**/*"]),
)
