package(default_visibility = ["//visibility:public"])

filegroup(
    name = "errors",
    srcs = glob(["errors/**/*"]),
)

filegroup(
    name = "syntax",
    srcs = glob(["syntax/**/*"]),
)

filegroup(
    name = "tokens",
    srcs = glob(["tokens/**/*"]),
)
